//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multi_controller.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Customisation : global::System.Configuration.ApplicationSettingsBase {
        
        private static Customisation defaultInstance = ((Customisation)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Customisation())));
        
        public static Customisation Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color MultiBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["MultiBorderColour"]));
            }
            set {
                this["MultiBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color LeftBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["LeftBorderColour"]));
            }
            set {
                this["LeftBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color RightBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["RightBorderColour"]));
            }
            set {
                this["RightBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color MultiClickBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["MultiClickBorderColour"]));
            }
            set {
                this["MultiClickBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 64, 0")]
        public global::System.Drawing.Color LeftMultiClickBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["LeftMultiClickBorderColour"]));
            }
            set {
                this["LeftMultiClickBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Olive")]
        public global::System.Drawing.Color RightMultiClickBorderColour {
            get {
                return ((global::System.Drawing.Color)(this["RightMultiClickBorderColour"]));
            }
            set {
                this["RightMultiClickBorderColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BorderWidth {
            get {
                return ((int)(this["BorderWidth"]));
            }
            set {
                this["BorderWidth"] = value;
            }
        }
    }
}
